-- Art Moment print-file privacy lifecycle.
-- Drafts expire after 7 days. Ordered files are scheduled for deletion after
-- the order is delivered, cancelled, or returned.

begin;

alter table public.settings
  add column if not exists print_draft_retention_days integer not null default 7,
  add column if not exists print_order_retention_days integer not null default 30;

do $print_retention_checks$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'settings_print_draft_retention_days_check'
  ) then
    alter table public.settings
      add constraint settings_print_draft_retention_days_check
      check (print_draft_retention_days between 1 and 30);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'settings_print_order_retention_days_check'
  ) then
    alter table public.settings
      add constraint settings_print_order_retention_days_check
      check (print_order_retention_days between 1 and 180);
  end if;
end;
$print_retention_checks$;

alter table public.print_drafts
  add column if not exists purge_after timestamptz,
  add column if not exists purge_reason text;

create index if not exists print_drafts_purge_after_idx
  on public.print_drafts(purge_after)
  where purge_after is not null;

create table if not exists public.print_file_deletion_logs (
  id bigint generated by default as identity primary key,
  draft_id uuid not null,
  store_order_id uuid,
  file_count integer not null default 0,
  total_bytes bigint not null default 0,
  reason text not null,
  deleted_at timestamptz not null default now()
);

alter table public.print_file_deletion_logs enable row level security;
revoke all on public.print_file_deletion_logs from anon, authenticated;
grant all on public.print_file_deletion_logs to authenticated;

drop policy if exists print_file_deletion_logs_admin_all on public.print_file_deletion_logs;
create policy print_file_deletion_logs_admin_all
  on public.print_file_deletion_logs for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create or replace function public.schedule_print_file_purge()
returns trigger
language plpgsql
security definer
set search_path = public
as $schedule_print_file_purge$
declare
  retention_days integer := 30;
begin
  select coalesce((
    select print_order_retention_days
    from public.settings
    order by id
    limit 1
  ), 30)
  into retention_days;

  if new.status::text in ('delivered', 'cancelled', 'returned') then
    update public.print_drafts
    set purge_after = coalesce(purge_after, now() + make_interval(days => retention_days)),
        purge_reason = new.status::text,
        updated_at = now()
    where store_order_id = new.id;
  elsif old.status::text in ('delivered', 'cancelled', 'returned') then
    update public.print_drafts
    set purge_after = null,
        purge_reason = null,
        updated_at = now()
    where store_order_id = new.id;
  end if;

  return new;
end;
$schedule_print_file_purge$;

drop trigger if exists store_orders_schedule_print_file_purge on public.store_orders;
create trigger store_orders_schedule_print_file_purge
after update of status on public.store_orders
for each row
when (old.status is distinct from new.status)
execute function public.schedule_print_file_purge();

-- Include print orders that reached a terminal state before this migration.
update public.print_drafts draft
set purge_after = coalesce(
      draft.purge_after,
      now() + make_interval(days => coalesce(settings.print_order_retention_days, 30))
    ),
    purge_reason = coalesce(draft.purge_reason, orders.status::text),
    updated_at = now()
from public.store_orders orders
cross join (
  select coalesce((
    select print_order_retention_days
    from public.settings
    order by id
    limit 1
  ), 30) as print_order_retention_days
) settings
where draft.store_order_id = orders.id
  and orders.status::text in ('delivered', 'cancelled', 'returned')
  and draft.purge_after is null;

-- Call this after adding Vault secrets named print_cleanup_function_url and
-- print_cleanup_cron_secret. It schedules the cleanup daily at 04:30 Riyadh.
create or replace function public.schedule_print_file_cleanup()
returns void
language plpgsql
security definer
set search_path = public, extensions
as $schedule_print_cleanup$
declare
  function_url text;
  cron_secret text;
  cron_command text;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.is_admin() then
    raise exception 'not_authorized';
  end if;
  if to_regnamespace('cron') is null or to_regnamespace('net') is null then
    raise exception 'cron_or_pg_net_extension_missing';
  end if;

  select decrypted_secret into function_url
  from vault.decrypted_secrets
  where name = 'print_cleanup_function_url'
  order by created_at desc
  limit 1;

  select decrypted_secret into cron_secret
  from vault.decrypted_secrets
  where name = 'print_cleanup_cron_secret'
  order by created_at desc
  limit 1;

  if nullif(trim(function_url), '') is null or nullif(trim(cron_secret), '') is null then
    raise exception 'print_cleanup_vault_secrets_missing';
  end if;

  begin
    perform cron.unschedule('cleanup-art-moment-print-files');
  exception when others then
    null;
  end;

  cron_command := format(
    'select net.http_post(url := %L, headers := jsonb_build_object(''Content-Type'', ''application/json'', ''x-cleanup-secret'', %L), body := ''{}''::jsonb);',
    function_url,
    cron_secret
  );
  perform cron.schedule('cleanup-art-moment-print-files', '30 1 * * *', cron_command);
end;
$schedule_print_cleanup$;

revoke all on function public.schedule_print_file_cleanup() from public;
grant execute on function public.schedule_print_file_cleanup() to authenticated, service_role;

comment on column public.settings.print_draft_retention_days is
  'Days before an unsubmitted print draft and its private files are deleted.';
comment on column public.settings.print_order_retention_days is
  'Days to retain private print files after delivery, cancellation, or return.';
comment on column public.print_drafts.purge_after is
  'Time after which the cleanup function permanently deletes originals and previews.';

commit;
