-- Art Moment store growth foundation:
-- product options, abandoned carts, purchase funnel analytics, and client error monitoring.

begin;

alter table public.products
  add column if not exists product_options jsonb not null default '[]'::jsonb,
  add column if not exists gallery_images jsonb not null default '[]'::jsonb,
  add column if not exists specifications jsonb not null default '{}'::jsonb;

do $product_json_checks$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'products_product_options_array_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_product_options_array_check
      check (jsonb_typeof(product_options) = 'array');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'products_gallery_images_array_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_gallery_images_array_check
      check (jsonb_typeof(gallery_images) = 'array');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'products_specifications_object_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_specifications_object_check
      check (jsonb_typeof(specifications) = 'object');
  end if;
end;
$product_json_checks$;

alter table public.store_order_items
  add column if not exists selected_options jsonb not null default '{}'::jsonb;

create table if not exists public.abandoned_carts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  anonymous_id text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  status text not null default 'active'
    check (status in ('active', 'converted', 'recovered', 'dismissed', 'expired')),
  last_activity_at timestamptz not null default now(),
  reminder_sent_at timestamptz,
  recovered_at timestamptz,
  converted_order_id uuid references public.store_orders(id) on delete set null,
  expires_at timestamptz not null default (now() + interval '30 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists abandoned_carts_active_customer_unique
  on public.abandoned_carts(customer_id)
  where status = 'active';
create index if not exists abandoned_carts_due_idx
  on public.abandoned_carts(last_activity_at, reminder_sent_at)
  where status = 'active';

create table if not exists public.store_funnel_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (
    event_name in (
      'store_visit', 'product_view', 'add_to_cart', 'cart_view',
      'login', 'checkout_started', 'order_created', 'payment_completed'
    )
  ),
  anonymous_id text not null,
  customer_id uuid references public.customers(id) on delete set null,
  session_id text,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists store_funnel_events_created_idx
  on public.store_funnel_events(created_at desc);
create index if not exists store_funnel_events_name_created_idx
  on public.store_funnel_events(event_name, created_at desc);

create table if not exists public.app_error_logs (
  id bigint generated by default as identity primary key,
  fingerprint text,
  source text not null default 'web',
  severity text not null default 'error' check (severity in ('warning', 'error', 'fatal')),
  message text not null,
  stack text,
  path text,
  anonymous_id text,
  customer_id uuid references public.customers(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  occurrence_count integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists app_error_logs_unresolved_idx
  on public.app_error_logs(last_seen_at desc)
  where resolved_at is null;

alter table public.abandoned_carts enable row level security;
alter table public.store_funnel_events enable row level security;
alter table public.app_error_logs enable row level security;

revoke all on public.abandoned_carts, public.store_funnel_events, public.app_error_logs
  from anon, authenticated;
grant all on public.abandoned_carts, public.store_funnel_events, public.app_error_logs
  to authenticated;

drop policy if exists abandoned_carts_admin_all on public.abandoned_carts;
create policy abandoned_carts_admin_all
  on public.abandoned_carts for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists store_funnel_events_admin_all on public.store_funnel_events;
create policy store_funnel_events_admin_all
  on public.store_funnel_events for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists app_error_logs_admin_all on public.app_error_logs;
create policy app_error_logs_admin_all
  on public.app_error_logs for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create or replace function public.track_store_funnel_event(
  p_event_name text,
  p_anonymous_id text,
  p_session_id text default null,
  p_path text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $track_store_funnel_event$
begin
  if octet_length(coalesce(p_metadata, '{}'::jsonb)::text) > 5000 then
    raise exception 'metadata_too_large';
  end if;

  if p_event_name not in (
    'store_visit', 'product_view', 'add_to_cart', 'cart_view',
    'login', 'checkout_started', 'order_created', 'payment_completed'
  ) then
    raise exception 'invalid_funnel_event';
  end if;

  if nullif(trim(coalesce(p_anonymous_id, '')), '') is null then
    raise exception 'invalid_anonymous_id';
  end if;

  if (
    select count(*)
    from public.store_funnel_events
    where anonymous_id = left(trim(p_anonymous_id), 100)
      and created_at >= now() - interval '1 hour'
  ) >= 300 then
    return;
  end if;

  insert into public.store_funnel_events (
    event_name, anonymous_id, session_id, path, metadata
  ) values (
    p_event_name,
    left(trim(p_anonymous_id), 100),
    left(nullif(trim(coalesce(p_session_id, '')), ''), 100),
    left(nullif(trim(coalesce(p_path, '')), ''), 500),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$track_store_funnel_event$;

create or replace function public.log_client_error(
  p_fingerprint text,
  p_message text,
  p_stack text default null,
  p_path text default null,
  p_anonymous_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $log_client_error$
declare
  normalized_fingerprint text;
begin
  if nullif(trim(coalesce(p_message, '')), '') is null then return; end if;
  if octet_length(coalesce(p_metadata, '{}'::jsonb)::text) > 5000 then return; end if;
  if (
    select count(*)
    from public.app_error_logs
    where anonymous_id = left(coalesce(p_anonymous_id, ''), 100)
      and created_at >= now() - interval '1 hour'
  ) >= 30 then
    return;
  end if;

  normalized_fingerprint := left(coalesce(nullif(trim(p_fingerprint), ''), md5(p_message)), 120);

  update public.app_error_logs
  set
    occurrence_count = occurrence_count + 1,
    last_seen_at = now(),
    path = left(coalesce(nullif(trim(p_path), ''), path), 500),
    metadata = coalesce(p_metadata, metadata)
  where id = (
    select id from public.app_error_logs
    where fingerprint = normalized_fingerprint and resolved_at is null
    order by last_seen_at desc
    limit 1
  );

  if not found then
    insert into public.app_error_logs (
      fingerprint, message, stack, path, anonymous_id, metadata
    ) values (
      normalized_fingerprint,
      left(trim(p_message), 1000),
      left(coalesce(p_stack, ''), 8000),
      left(coalesce(p_path, ''), 500),
      left(coalesce(p_anonymous_id, ''), 100),
      coalesce(p_metadata, '{}'::jsonb)
    );
  end if;
end;
$log_client_error$;

revoke all on function public.track_store_funnel_event(text, text, text, text, jsonb) from public;
revoke all on function public.log_client_error(text, text, text, text, text, jsonb) from public;
grant execute on function public.track_store_funnel_event(text, text, text, text, jsonb)
  to anon, authenticated;
grant execute on function public.log_client_error(text, text, text, text, text, jsonb)
  to anon, authenticated;

commit;
