-- Secure public order tracking for print and store orders.

begin;

create extension if not exists pgcrypto;

alter table public.orders
  add column if not exists tracking_access_token text;

alter table public.store_orders
  add column if not exists tracking_access_token text;

update public.orders
set tracking_access_token = encode(gen_random_bytes(16), 'hex')
where tracking_access_token is null or length(trim(tracking_access_token)) < 24;

update public.store_orders
set tracking_access_token = encode(gen_random_bytes(16), 'hex')
where tracking_access_token is null or length(trim(tracking_access_token)) < 24;

alter table public.orders
  alter column tracking_access_token set default encode(gen_random_bytes(16), 'hex'),
  alter column tracking_access_token set not null;

alter table public.store_orders
  alter column tracking_access_token set default encode(gen_random_bytes(16), 'hex'),
  alter column tracking_access_token set not null;

create unique index if not exists orders_tracking_access_token_key
  on public.orders (tracking_access_token);

create unique index if not exists store_orders_tracking_access_token_key
  on public.store_orders (tracking_access_token);

create table if not exists public.public_tracking_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  order_key_hash text not null,
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists public_tracking_attempts_rate_idx
  on public.public_tracking_attempts (ip_hash, created_at desc);

alter table public.public_tracking_attempts enable row level security;
revoke all on public.public_tracking_attempts from anon, authenticated;
grant all on public.public_tracking_attempts to authenticated;

drop policy if exists public_tracking_attempts_admin_all on public.public_tracking_attempts;
create policy public_tracking_attempts_admin_all
on public.public_tracking_attempts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.store_order_status_history (
  id uuid primary key default gen_random_uuid(),
  store_order_id uuid not null references public.store_orders(id) on delete cascade,
  status text not null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists store_order_status_history_order_idx
  on public.store_order_status_history (store_order_id, created_at asc);

alter table public.store_order_status_history enable row level security;
revoke all on public.store_order_status_history from anon, authenticated;
grant all on public.store_order_status_history to authenticated;

drop policy if exists store_order_status_history_admin_all on public.store_order_status_history;
create policy store_order_status_history_admin_all
on public.store_order_status_history
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create or replace function public.log_store_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.store_order_status_history (store_order_id, status, created_at)
    values (
      new.id,
      coalesce(new.status::text, 'pending_verification'),
      coalesce(new.created_at, now())
    );
  elsif old.status is distinct from new.status then
    insert into public.store_order_status_history (store_order_id, status, created_at)
    values (new.id, coalesce(new.status::text, 'pending_verification'), now());
  end if;
  return new;
end;
$$;

drop trigger if exists store_orders_status_history_trigger on public.store_orders;
create trigger store_orders_status_history_trigger
after insert or update of status on public.store_orders
for each row execute function public.log_store_order_status_change();

insert into public.store_order_status_history (store_order_id, status, created_at)
select store_order.id, coalesce(store_order.status::text, 'pending_verification'), coalesce(store_order.created_at, now())
from public.store_orders store_order
where not exists (
  select 1
  from public.store_order_status_history history
  where history.store_order_id = store_order.id
);

commit;
